/** @format */

import type { Metadata } from "next";
import "./globals.css";
import { midtrans_client_key } from "@/helpers/config";

export const metadata: Metadata = {
  title: "Kick Avenue - Sneakers, Apparel, Luxury, Fashion, Collectibles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          src="https://app.sandbox.midtrans.com/snap/snap.js"
          data-client-key={midtrans_client_key}
          defer
        ></script>
      </head>
      <body>{children}</body>
    </html>
  );
}
